### ISSUE TITLE
redis proxy

### ISSUE THREAD

**Issue by lonoak** [iusrepo/redis5#2]
Hi,

I'm relatively new to redis, so I'm not 100% sure the redis architecture I have in mind is correct. The idea is to use [redis proxy](https://github.com/RedisLabs/redis-cluster-proxy) to connect clients to a redis cluster created using the redis5 package:

```clients <--> redis cluster proxy <--> {redis cluster}```

If this is not a crazy idea, then it comes my question... do you foresee redis cluster proxy could be included within the redis5 package?

I could also try to create a separate package (sort of `redis5-proxy`) if it is considered interesting.

Thanks,

Jose.

**Comment by carlwgeorge** [comment]
I'm also not an expert on redis architecture.  It appears that redis-cluster-proxy is versioned independently of redis itself, so including it in the redis5 package isn't appropriate.

https://github.com/redislabs/redis-cluster-proxy/releases

A separate package for this would make sense, but since that doesn't already exist in RHEL or EPEL, it's out of scope for IUS.  The best way forward would be to get the software added to Fedora, and then create and epel7 branch.  As far as I can tell, that would be compatible with either redis (version 3.x.x) in EPEL or redis5 from IUS.
